### ISSUE TITLE
invalid while number bigger than 10^16

### ISSUE THREAD

**Issue by wangsenyan** [utkarsh-pro/nodejs-snowflake#11]
invalid while number bigger than 10^16

 const uid = new UniqueID({
   customEpoch: new Date('2021-08-31').getTime(),
   returnNumber: true,
   machineID: getNum(getMac()),
});

 function generate() {
  return Number(uid.getUniqueID());
}

**Comment by tangledbytes** [comment]
Thank you for creating the issue @wangsenyan. I see that you have specified `returnNumber: true`, this will ensure that the function returns a `BigInt`.

Coming to the issue you are facing, in the `generate` function you have casted the returned value to `Number`. Javascript `Number` can unfortunately hold value only upto `9 * 10^15` but as the library will always returns a 64 bit value, this casting will most likely produce invalid values.

**How to solve this then?**
You can do either of the two things
1. Don't use `returnNumber: true`, the function will then return id as string.
2. Don't cast the value to `Number`
