### ISSUE TITLE
Precompile Binaries

### ISSUE THREAD

**Issue by mkadirtan** [utkarsh-pro/nodejs-snowflake#12]
Can you please publish precompiled binaries for arm64. It is not so easy to install with m1.
`gyp: No Xcode or CLT version detected!`

**Comment by tangledbytes** [comment]
@mkadirtan that's a great suggestion. Will add the precompiled binaries for arm64 soon.

**Comment by tangledbytes** [comment]
@mkadirtan added the new assets to the release. Kindly close the issue if it solves your issue.

**Comment by mkadirtan** [comment]
Thank you!
