### ISSUE TITLE
Visual Studio needed to install??

### ISSUE THREAD

**Issue by ghost** [utkarsh-pro/nodejs-snowflake#13]
![image](https://user-images.githubusercontent.com/74330895/148666768-9820fa3f-adef-4ee1-b842-f14327a3ffe5.png)

**Comment by tangledbytes** [comment]
@Crafter-san took a while to respond to this issue. `nodejs-snowflake` v2.0.0 fixes the above issue and significantly improves (roughly 120% increase).

**Comment by tangledbytes** [comment]
Kindly close the issue if it is working for you now...
