### ISSUE TITLE
Issue in type definitions (semicolon)

### ISSUE THREAD

**Issue by OfficialCRUGG** [utkarsh-pro/nodejs-snowflake#16]
Hello there, I added `nodejs-snowflake` to a TypeScript project and it doesn't compile anymore due to the following error:

```
node_modules/nodejs-snowflake/nodejs_snowflake.d.ts(7,2): error TS1036: Statements are not allowed in ambient contexts.
```

This is due to the semicolon in line 7 of `nodejs_snowflake.d.ts`. If I manually remove this, my project compiles just fine.

**Comment by tangledbytes** [comment]
@OfficialCRUGG see if v2.0.1 fixes your issues.

**Comment by OfficialCRUGG** [comment]
Works! Thanks!
