### ISSUE TITLE
Use the getUniqueID method to generate an id that ends in n

### ISSUE THREAD

**Issue by lishaoshi** [utkarsh-pro/nodejs-snowflake#20]
Use the getUniqueID method to generate an id that ends in n

**Comment by tangledbytes** [comment]
@lishaoshi, I am not sure I understand. Is your question that why the IDs are ending with `n`?

**Comment by sequencerr** [comment]
> Use the getUniqueID method to generate an id that ends in n

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

A BigInt value, also sometimes just called a BigInt, is a bigint [primitive](https://developer.mozilla.org/en-US/docs/Glossary/Primitive), created by appending **`n`** to the end of an integer literal, or ...
