### ISSUE TITLE
Production readiness

### ISSUE THREAD

**Issue by helloanoop** [utkarsh-pro/nodejs-snowflake#6]
Thanks Utkarsh for your work on this.

I was looking for a snowflake ID generator.
Are you using this in production?
Just checking if you forsee any issues for use in production.

**Comment by tangledbytes** [comment]
Hi @anoopmd. Yes, nodejs-snowflake is getting used internally at my own organization (Hackstrap) and as far as I know it is also getting used at a few other organziations. 

We haven't faced any issues using this in production neither have I heard of issues from the others :slightly_smiling_face: .

The only thing that I have heard a few complaints about is the installation process as it requires a few basic C++ utilities to be present which is not usually present in linux distros like `alpine linux`.

**Comment by helloanoop** [comment]
Thanks @utkarsh-pro !
