### ISSUE TITLE
C++ to WASM

### ISSUE THREAD

**Issue by nikitapilgrim** [utkarsh-pro/nodejs-snowflake#9]
Hello, thank you for the library
Is it possible to transfer the main id generation function to WASM? Need it for cases with cloudflare worker and running in a browser
https://medium.com/netscape/javascript-c-modern-ways-to-use-c-in-javascript-projects-a19003c5a9ff

**Comment by tangledbytes** [comment]
@nikitapilgrim that's a great suggestion. Moving away from N-API interface to WASI interface (WASM) is in the roadmap for the next release, i.e v1.6.3.

**Comment by 0xdpfly** [comment]
When I walked through the tests, I encountered a situation where duplicate ids were generated。
![image](https://user-images.githubusercontent.com/25901010/136645013-b8085be8-5a15-4f11-b56b-b4d9343b5e42.png)
![image](https://user-images.githubusercontent.com/25901010/136645038-c9553f4b-33ec-41f7-8115-b1f1d7b53401.png)
![image](https://user-images.githubusercontent.com/25901010/136645046-355ccb15-5557-4aa3-a2bf-4889570a69ed.png)

**Comment by tangledbytes** [comment]
@nikitapilgrim, that's an interesting observation. Can you please do me a favour and repeat the test ensuring the following:
1. Use the same instance of `UniqueID` through out the test.
2. Pass in the node id manually in the constructor.

The reason for the above request is that when you don't provide a node id manually, nodejs-snowflake automatically generates one for you, this is a pseudorandom number between 0 - 4095. What could be happening with your tests is, two different instances of `UniqueID` initialised with different node ids overlapped in such a manner that they produced the same IDs.

**Comment by 0xdpfly** [comment]
thanks，I've solved it.

**Comment by tangledbytes** [comment]
@nikitapilgrim `v2.0.0` of `nodejs-snowflake` is now written in Rust and is complied to WASM. The published package is for `nodejs` but I have also published compiled WASM with the release assets, which you can run directly in browser without any issues.

Checkout if this is still of interest to you...
